// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A request to perform a batch of search operations.
public struct BatchSearchDataObjectsRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the Collection for which to search.
  /// Format: `projects/{project}/locations/{location}/collections/{collection}`
  public var parent: Swift.String = Swift.String()

  /// Required. A list of search requests to execute in parallel.
  public var searches: [Search] = []

  /// Optional. Options for combining the results of the batch search operations.
  public var combine: BatchSearchDataObjectsRequest.CombineResultsOptions? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BatchSearchDataObjectsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchSearchDataObjectsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let searches = CodingKeys(stringValue: "searches")
    static let combine = CodingKeys(stringValue: "combine")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "searches",
      "combine",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent([Search].self, forKey: .searches) {
      self.searches = value
    }
    self.combine = try container.decodeIfPresent(
      BatchSearchDataObjectsRequest.CombineResultsOptions.self, forKey: .combine)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.searches, forKey: .searches)
    try container.encodeIfPresent(self.combine, forKey: .combine)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Options for combining the results of the batch search operations.
  public struct CombineResultsOptions: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The ranker to use for combining the results.
    public var ranker: Ranker? = nil

    /// Optional. Mask specifying which fields to return.
    public var outputFields: OutputFields? = nil

    /// Optional. The number of results to return. If not set, a default value
    /// will be used.
    public var topK: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CombineResultsOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CombineResultsOptions().with { $0.ranker = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let ranker = CodingKeys(stringValue: "ranker")
      static let outputFields = CodingKeys(stringValue: "outputFields")
      static let topK = CodingKeys(stringValue: "topK")

      static let _knownKeys: Set<Swift.String> = [
        "ranker",
        "outputFields",
        "topK",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.ranker = try container.decodeIfPresent(Ranker.self, forKey: .ranker)
      self.outputFields = try container.decodeIfPresent(OutputFields.self, forKey: .outputFields)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .topK) {
        self.topK = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.ranker, forKey: .ranker)
      try container.encodeIfPresent(self.outputFields, forKey: .outputFields)
      try container.encode(self.topK, forKey: .topK)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.vectorsearch.v1.BatchSearchDataObjectsRequest.CombineResultsOptions"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vectorsearch.v1.BatchSearchDataObjectsRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
