// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Message describing Collection object
public struct Collection: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. name of resource
  public var name: Swift.String = Swift.String()

  /// Optional. User-specified display name of the collection
  public var displayName: Swift.String = Swift.String()

  /// Optional. User-specified description of the collection
  public var description: Swift.String = Swift.String()

  /// Output only. [Output only] Create time stamp
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. [Output only] Update time stamp
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Labels as key value pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Schema for vector fields. Only vector fields in this schema will
  /// be searchable. Field names must contain only alphanumeric characters,
  /// underscores, and hyphens.
  public var vectorSchema: [Swift.String: VectorField] = [:]

  /// Optional. JSON Schema for data.
  /// Field names must contain only alphanumeric characters,
  /// underscores, and hyphens.
  /// The schema must be compliant with
  /// [JSON Schema Draft 7](https://json-schema.org/draft-07/schema).
  public var dataSchema: GoogleCloudWkt.Struct? = nil

  /// Optional. Immutable. Specifies the customer-managed encryption key spec for
  /// a Collection. If set, this Collection and all sub-resources of this
  /// Collection will be secured by this key.
  public var encryptionSpec: EncryptionSpec? = nil

  /// Initialize a new instance of `Collection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Collection().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vectorsearch.v1.Collection"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
