// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service for searching data objects.
///
/// @Snippet(path: "DataObjectSearchServiceQuickstart")
public final class DataObjectSearchServiceClient: Clients.DataObjectSearchServiceProtocol, Sendable
{
  let inner: any Clients.DataObjectSearchServiceStub

  /// Creates a new `DataObjectSearchServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.DataObjectSearchServiceStub =
      try Clients.DataObjectSearchServiceTransport(options)
    inner = Clients.DataObjectSearchServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.DataObjectSearchServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Searches data objects.
  ///
  /// @Snippet(path: "DataObjectSearchService_SearchDataObjects")
  public func searchDataObjects(
    request: SearchDataObjectsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVectorSearchV1.SearchDataObjectsResponse {
    try await self.inner.searchDataObjects(request: request, options: options)
  }

  /// Queries data objects.
  ///
  /// @Snippet(path: "DataObjectSearchService_QueryDataObjects")
  public func queryDataObjects(
    request: QueryDataObjectsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVectorSearchV1.QueryDataObjectsResponse {
    try await self.inner.queryDataObjects(request: request, options: options)
  }

  /// Aggregates data objects.
  ///
  /// @Snippet(path: "DataObjectSearchService_AggregateDataObjects")
  public func aggregateDataObjects(
    request: AggregateDataObjectsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVectorSearchV1.AggregateDataObjectsResponse {
    try await self.inner.aggregateDataObjects(request: request, options: options)
  }

  /// Batch searches data objects.
  ///
  /// @Snippet(path: "DataObjectSearchService_BatchSearchDataObjects")
  public func batchSearchDataObjects(
    request: BatchSearchDataObjectsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVectorSearchV1.BatchSearchDataObjectsResponse {
    try await self.inner.batchSearchDataObjects(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "DataObjectSearchService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "DataObjectSearchService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DataObjectSearchService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DataObjectSearchService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DataObjectSearchService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DataObjectSearchService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `DataObjectSearchServiceClient`.
  ///
  /// To mock `DataObjectSearchServiceClient` change your functions to receive
  /// `some DataObjectSearchServiceProtocol` or `any DataObjectSearchServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol DataObjectSearchServiceProtocol: Sendable {
    /// See `DataObjectSearchServiceClient.searchDataObjects`.
    func searchDataObjects(
      request: SearchDataObjectsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVectorSearchV1.SearchDataObjectsResponse

    /// See `DataObjectSearchServiceClient.queryDataObjects`.
    func queryDataObjects(
      request: QueryDataObjectsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVectorSearchV1.QueryDataObjectsResponse

    /// See `DataObjectSearchServiceClient.aggregateDataObjects`.
    func aggregateDataObjects(
      request: AggregateDataObjectsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVectorSearchV1.AggregateDataObjectsResponse

    /// See `DataObjectSearchServiceClient.batchSearchDataObjects`.
    func batchSearchDataObjects(
      request: BatchSearchDataObjectsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVectorSearchV1.BatchSearchDataObjectsResponse

    /// See `DataObjectSearchServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `DataObjectSearchServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `DataObjectSearchServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `DataObjectSearchServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `DataObjectSearchServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.DataObjectSearchServiceProtocol {
  public func searchDataObjects(request: SearchDataObjectsRequest) async throws
    -> GoogleCloudVectorSearchV1.SearchDataObjectsResponse
  {
    try await self.searchDataObjects(request: request, options: .init())
  }

  public func searchDataObjects(
    request: SearchDataObjectsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVectorSearchV1.SearchDataObjectsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func searchDataObjectsByItems(
    request: SearchDataObjectsRequest
  ) -> any AsyncSequence<SearchResult, Swift.Error> {
    self.searchDataObjectsByItems(request: request, options: .init())
  }

  /// Searches data objects.
  ///
  /// @Snippet(path: "DataObjectSearchService_SearchDataObjects")
  public func searchDataObjectsByItems(
    request: SearchDataObjectsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<SearchResult, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVectorSearchV1.SearchDataObjectsResponse in
      var request = request
      request.pageToken = token
      return try await self.searchDataObjects(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func queryDataObjects(request: QueryDataObjectsRequest) async throws
    -> GoogleCloudVectorSearchV1.QueryDataObjectsResponse
  {
    try await self.queryDataObjects(request: request, options: .init())
  }

  public func queryDataObjects(
    request: QueryDataObjectsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVectorSearchV1.QueryDataObjectsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func queryDataObjectsByItems(
    request: QueryDataObjectsRequest
  ) -> any AsyncSequence<DataObject, Swift.Error> {
    self.queryDataObjectsByItems(request: request, options: .init())
  }

  /// Queries data objects.
  ///
  /// @Snippet(path: "DataObjectSearchService_QueryDataObjects")
  public func queryDataObjectsByItems(
    request: QueryDataObjectsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<DataObject, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVectorSearchV1.QueryDataObjectsResponse in
      var request = request
      request.pageToken = token
      return try await self.queryDataObjects(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func aggregateDataObjects(request: AggregateDataObjectsRequest) async throws
    -> GoogleCloudVectorSearchV1.AggregateDataObjectsResponse
  {
    try await self.aggregateDataObjects(request: request, options: .init())
  }

  public func aggregateDataObjects(
    request: AggregateDataObjectsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVectorSearchV1.AggregateDataObjectsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func batchSearchDataObjects(request: BatchSearchDataObjectsRequest) async throws
    -> GoogleCloudVectorSearchV1.BatchSearchDataObjectsResponse
  {
    try await self.batchSearchDataObjects(request: request, options: .init())
  }

  public func batchSearchDataObjects(
    request: BatchSearchDataObjectsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVectorSearchV1.BatchSearchDataObjectsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "DataObjectSearchService_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DataObjectSearchService_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
