// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A dataObject resource in Vector Search.
public struct DataObject: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The fully qualified resource name of the dataObject.
  ///
  /// Format:
  /// `projects/{project}/locations/{location}/collections/{collection}/dataObjects/{data_object_id}`
  /// The data_object_id must be 1-63 characters
  /// long, and comply with [RFC1035](https://www.ietf.org/rfc/rfc1035.txt).
  public var name: Swift.String = Swift.String()

  /// Output only. The id of the dataObject.
  public var dataObjectId: Swift.String = Swift.String()

  /// Output only. Timestamp the dataObject was created at.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Timestamp the dataObject was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. The data of the dataObject.
  public var data: GoogleWKT.WKTStruct? = nil

  /// Optional. The vectors of the dataObject.
  public var vectors: [Swift.String: Vector] = [:]

  /// Optional. The etag of the dataObject.
  public var etag: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DataObject`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataObject().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let dataObjectId = CodingKeys(stringValue: "dataObjectId")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let data = CodingKeys(stringValue: "data")
    static let vectors = CodingKeys(stringValue: "vectors")
    static let etag = CodingKeys(stringValue: "etag")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "dataObjectId",
      "createTime",
      "updateTime",
      "data",
      "vectors",
      "etag",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dataObjectId) {
      self.dataObjectId = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    self.data = try container.decodeIfPresent(GoogleWKT.WKTStruct.self, forKey: .data)
    if let value = try container.decodeIfPresent([Swift.String: Vector].self, forKey: .vectors) {
      self.vectors = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.dataObjectId, forKey: .dataObjectId)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.data, forKey: .data)
    try container.encode(self.vectors, forKey: .vectors)
    try container.encode(self.etag, forKey: .etag)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vectorsearch.v1.DataObject"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
