// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A dataObject resource in Vector Search.
public struct DataObject: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The fully qualified resource name of the dataObject.
  ///
  /// Format:
  /// `projects/{project}/locations/{location}/collections/{collection}/dataObjects/{data_object_id}`
  /// The data_object_id must be 1-63 characters
  /// long, and comply with [RFC1035](https://www.ietf.org/rfc/rfc1035.txt).
  public var name: Swift.String = Swift.String()

  /// Output only. The id of the dataObject.
  public var dataObjectId: Swift.String = Swift.String()

  /// Output only. Timestamp the dataObject was created at.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Timestamp the dataObject was last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. The data of the dataObject.
  public var data: GoogleCloudWKT.Struct? = nil

  /// Optional. The vectors of the dataObject.
  public var vectors: [Swift.String: Vector] = [:]

  /// Optional. The etag of the dataObject.
  public var etag: Swift.String = Swift.String()

  /// Initialize a new instance of `DataObject`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataObject().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vectorsearch.v1.DataObject"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
