// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for
/// [VectorSearchService.ImportDataObjects][google.cloud.vectorsearch.v1.VectorSearchService.ImportDataObjects].
///
/// [google.cloud.vectorsearch.v1.VectorSearchService.ImportDataObjects]: <doc:VectorSearchServiceClient/importDataObjects(request:options:)>
public struct ImportDataObjectsRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the Collection to import DataObjects into.
  /// Format: `projects/{project}/locations/{location}/collections/{collection}`.
  public var name: Swift.String = Swift.String()

  /// The configuration for the import data and error results.
  public var config: ConfigOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ImportDataObjectsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImportDataObjectsRequest().with { $0.gcsImport = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gcsImport = CodingKeys(stringValue: "gcsImport")
    static let name = CodingKeys(stringValue: "name")

    static let _knownKeys: Set<Swift.String> = [
      "gcsImport",
      "name",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }

    var config: ConfigOneOf? = nil
    let configCheckAndSet = {
      if config != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'config'"))
      }
      config = $0
    }
    if let gcsImport = try container.decodeIfPresent(
      ImportDataObjectsRequest.GcsImportConfig?.self, forKey: .gcsImport)
    {
      try configCheckAndSet(.gcsImport(gcsImport))
    }
    self.config = config
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)

    if let choice = self.config {
      switch choice {
      case .gcsImport(let value):
        try container.encode(value, forKey: .gcsImport)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Google Cloud Storage configuration for the import.
  public struct GcsImportConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. URI prefix of the Cloud Storage DataObjects to import.
    public var contentsUri: Swift.String = Swift.String()

    /// Required. URI prefix of the Cloud Storage location to write any errors
    /// encountered during the import.
    public var errorUri: Swift.String = Swift.String()

    /// Optional. URI prefix of the Cloud Storage location to write DataObject
    /// `IDs` and `etags` of DataObjects that were successfully imported. The
    /// service will write the successfully imported DataObjects to sharded files
    /// under this prefix. If this field is empty, no output will be written.
    public var outputUri: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GcsImportConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GcsImportConfig().with { $0.contentsUri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let contentsUri = CodingKeys(stringValue: "contentsUri")
      static let errorUri = CodingKeys(stringValue: "errorUri")
      static let outputUri = CodingKeys(stringValue: "outputUri")

      static let _knownKeys: Set<Swift.String> = [
        "contentsUri",
        "errorUri",
        "outputUri",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .contentsUri) {
        self.contentsUri = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .errorUri) {
        self.errorUri = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .outputUri) {
        self.outputUri = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.contentsUri, forKey: .contentsUri)
      try container.encode(self.errorUri, forKey: .errorUri)
      try container.encode(self.outputUri, forKey: .outputUri)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.vectorsearch.v1.ImportDataObjectsRequest.GcsImportConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The configuration for the import data and error results.
  public enum ConfigOneOf: Codable, Equatable, Sendable {
    /// The Cloud Storage location of the input content.
    indirect case gcsImport(ImportDataObjectsRequest.GcsImportConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vectorsearch.v1.ImportDataObjectsRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
