// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Message describing Index object
public struct Index: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. name of resource
  public var name: Swift.String = Swift.String()

  /// Optional. User-specified display name of the index
  public var displayName: Swift.String = Swift.String()

  /// Optional. User-specified description of the index
  public var description: Swift.String = Swift.String()

  /// Optional. Labels as key value pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. [Output only] Create time stamp
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. [Output only] Update time stamp
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Distance metric used for indexing. If not specified, will default
  /// to DOT_PRODUCT.
  public var distanceMetric: DistanceMetric = DistanceMetric()

  /// Required. The collection schema field to index.
  public var indexField: Swift.String = Swift.String()

  /// Optional. The fields to push into the index to enable fast ANN inline
  /// filtering.
  public var filterFields: [Swift.String] = []

  /// Optional. The fields to push into the index to enable inline data
  /// retrieval.
  public var storeFields: [Swift.String] = []

  /// The infrastructure type of the index.
  public var infraType: OneOf_InfraType? = nil

  /// The type of the index.
  public var indexType: OneOf_IndexType? = nil

  /// Initialize a new instance of `Index`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Index().with { $0.dedicatedInfrastructure = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case dedicatedInfrastructure = "dedicatedInfrastructure"
    case denseScann = "denseScann"
    case name = "name"
    case displayName = "displayName"
    case description = "description"
    case labels = "labels"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case distanceMetric = "distanceMetric"
    case indexField = "indexField"
    case filterFields = "filterFields"
    case storeFields = "storeFields"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .updateTime)
    self.distanceMetric = try container.decode(DistanceMetric.self, forKey: .distanceMetric)
    self.indexField = try container.decode(Swift.String.self, forKey: .indexField)
    self.filterFields = try container.decode([Swift.String].self, forKey: .filterFields)
    self.storeFields = try container.decode([Swift.String].self, forKey: .storeFields)

    var infraType: OneOf_InfraType? = nil
    let infraTypeCheckAndSet = {
      if infraType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'infraType'"))
      }
      infraType = $0
    }
    if let dedicatedInfrastructure = try container.decodeIfPresent(
      DedicatedInfrastructure?.self, forKey: .dedicatedInfrastructure)
    {
      try infraTypeCheckAndSet(.dedicatedInfrastructure(dedicatedInfrastructure))
    }
    self.infraType = infraType

    var indexType: OneOf_IndexType? = nil
    let indexTypeCheckAndSet = {
      if indexType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'indexType'"))
      }
      indexType = $0
    }
    if let denseScann = try container.decodeIfPresent(DenseScannIndex?.self, forKey: .denseScann) {
      try indexTypeCheckAndSet(.denseScann(denseScann))
    }
    self.indexType = indexType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.distanceMetric, forKey: .distanceMetric)
    try container.encode(self.indexField, forKey: .indexField)
    try container.encode(self.filterFields, forKey: .filterFields)
    try container.encode(self.storeFields, forKey: .storeFields)

    if let choice = self.infraType {
      switch choice {
      case .dedicatedInfrastructure(let value):
        try container.encode(value, forKey: .dedicatedInfrastructure)
      }
    }

    if let choice = self.indexType {
      switch choice {
      case .denseScann(let value):
        try container.encode(value, forKey: .denseScann)
      }
    }
  }

  /// The infrastructure type of the index.
  public enum OneOf_InfraType: Codable, Equatable, Sendable {
    /// Optional. Dedicated infrastructure for the index.
    indirect case dedicatedInfrastructure(DedicatedInfrastructure?)
  }

  /// The type of the index.
  public enum OneOf_IndexType: Codable, Equatable, Sendable {
    /// Optional. Dense ScaNN index.
    indirect case denseScann(DenseScannIndex?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vectorsearch.v1.Index"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
