// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Defines a ranker to combine results from multiple searches.
public struct Ranker: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The ranking method to use.
  public var ranker: OneOf_Ranker? = nil

  /// Initialize a new instance of `Ranker`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Ranker().with { $0.rrf = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case rrf = "rrf"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var ranker: OneOf_Ranker? = nil
    let rankerCheckAndSet = {
      if ranker != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'ranker'"))
      }
      ranker = $0
    }
    if let rrf = try container.decodeIfPresent(ReciprocalRankFusion?.self, forKey: .rrf) {
      try rankerCheckAndSet(.rrf(rrf))
    }
    self.ranker = ranker
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.ranker {
      switch choice {
      case .rrf(let value):
        try container.encode(value, forKey: .rrf)
      }
    }
  }

  /// The ranking method to use.
  public enum OneOf_Ranker: Codable, Equatable, Sendable {
    /// Reciprocal Rank Fusion ranking.
    indirect case rrf(ReciprocalRankFusion?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vectorsearch.v1.Ranker"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
