// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A single search request within a batch operation.
public struct Search: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The type of search to perform.
  public var searchType: OneOf_SearchType? = nil

  /// Initialize a new instance of `Search`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Search().with { $0.vectorSearch = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case vectorSearch = "vectorSearch"
    case semanticSearch = "semanticSearch"
    case textSearch = "textSearch"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var searchType: OneOf_SearchType? = nil
    let searchTypeCheckAndSet = {
      if searchType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'searchType'"))
      }
      searchType = $0
    }
    if let vectorSearch = try container.decodeIfPresent(VectorSearch?.self, forKey: .vectorSearch) {
      try searchTypeCheckAndSet(.vectorSearch(vectorSearch))
    }
    if let semanticSearch = try container.decodeIfPresent(
      SemanticSearch?.self, forKey: .semanticSearch)
    {
      try searchTypeCheckAndSet(.semanticSearch(semanticSearch))
    }
    if let textSearch = try container.decodeIfPresent(TextSearch?.self, forKey: .textSearch) {
      try searchTypeCheckAndSet(.textSearch(textSearch))
    }
    self.searchType = searchType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.searchType {
      switch choice {
      case .vectorSearch(let value):
        try container.encode(value, forKey: .vectorSearch)
      case .semanticSearch(let value):
        try container.encode(value, forKey: .semanticSearch)
      case .textSearch(let value):
        try container.encode(value, forKey: .textSearch)
      }
    }
  }

  /// The type of search to perform.
  public enum OneOf_SearchType: Codable, Equatable, Sendable {
    /// A vector-based search.
    indirect case vectorSearch(VectorSearch?)
    /// A semantic search.
    indirect case semanticSearch(SemanticSearch?)
    /// A text search operation.
    indirect case textSearch(TextSearch?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vectorsearch.v1.Search"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
