// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Request for performing a single search.
public struct SearchDataObjectsRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the Collection for which to search.
  /// Format: `projects/{project}/locations/{location}/collections/{collection}`
  public var parent: Swift.String = Swift.String()

  /// Optional. The standard list page size. Only supported for KNN. If not set,
  /// up to search_type.top_k results will be returned. The maximum value is
  /// 1000; values above 1000 will be coerced to 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. The standard list page token.
  /// Typically obtained via
  /// [SearchDataObjectsResponse.next_page_token][google.cloud.vectorsearch.v1.SearchDataObjectsResponse.next_page_token]
  /// of the previous
  /// [DataObjectSearchService.SearchDataObjects][google.cloud.vectorsearch.v1.DataObjectSearchService.SearchDataObjects]
  /// call.
  ///
  /// [google.cloud.vectorsearch.v1.DataObjectSearchService.SearchDataObjects]: <doc:DataObjectSearchServiceClient/searchDataObjects(request:options:)>
  /// [google.cloud.vectorsearch.v1.SearchDataObjectsResponse.next_page_token]: <doc:SearchDataObjectsResponse/nextPageToken>
  public var pageToken: Swift.String = Swift.String()

  /// The query to search for.
  public var searchType: OneOf_SearchType? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SearchDataObjectsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchDataObjectsRequest().with { $0.vectorSearch = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let vectorSearch = CodingKeys(stringValue: "vectorSearch")
    static let semanticSearch = CodingKeys(stringValue: "semanticSearch")
    static let textSearch = CodingKeys(stringValue: "textSearch")
    static let parent = CodingKeys(stringValue: "parent")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")

    static let _knownKeys: Set<Swift.String> = [
      "vectorSearch",
      "semanticSearch",
      "textSearch",
      "parent",
      "pageSize",
      "pageToken",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }

    var searchType: OneOf_SearchType? = nil
    let searchTypeCheckAndSet = {
      if searchType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'searchType'"))
      }
      searchType = $0
    }
    if let vectorSearch = try container.decodeIfPresent(VectorSearch?.self, forKey: .vectorSearch) {
      try searchTypeCheckAndSet(.vectorSearch(vectorSearch))
    }
    if let semanticSearch = try container.decodeIfPresent(
      SemanticSearch?.self, forKey: .semanticSearch)
    {
      try searchTypeCheckAndSet(.semanticSearch(semanticSearch))
    }
    if let textSearch = try container.decodeIfPresent(TextSearch?.self, forKey: .textSearch) {
      try searchTypeCheckAndSet(.textSearch(textSearch))
    }
    self.searchType = searchType
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)

    if let choice = self.searchType {
      switch choice {
      case .vectorSearch(let value):
        try container.encode(value, forKey: .vectorSearch)
      case .semanticSearch(let value):
        try container.encode(value, forKey: .semanticSearch)
      case .textSearch(let value):
        try container.encode(value, forKey: .textSearch)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The query to search for.
  public enum OneOf_SearchType: Codable, Equatable, Sendable {
    /// A vector search operation.
    indirect case vectorSearch(VectorSearch?)
    /// A semantic search operation.
    indirect case semanticSearch(SemanticSearch?)
    /// Optional. A text search operation.
    indirect case textSearch(TextSearch?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vectorsearch.v1.SearchDataObjectsRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
