// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Defines a semantic search operation.
public struct SemanticSearch: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The query text, which is used to generate an embedding according
  /// to the embedding model specified in the collection config.
  public var searchText: Swift.String = Swift.String()

  /// Required. The vector field to search.
  public var searchField: Swift.String = Swift.String()

  /// Required. The task type of the query embedding.
  public var taskType: EmbeddingTaskType = EmbeddingTaskType()

  /// Optional. The fields to return in the search results.
  public var outputFields: OutputFields? = nil

  /// Optional. A JSON filter expression, e.g. {"genre": {"$eq": "sci-fi"}},
  /// represented as a google.protobuf.Struct.
  public var filter: GoogleWKT.Struct? = nil

  /// Optional. The number of data objects to return.
  public var topK: Swift.Int32? = nil

  /// Optional. Sets the search hint. If no strategy is specified, the service
  /// will use an index if one is available, and fall back to KNN search
  /// otherwise.
  public var searchHint: SearchHint? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SemanticSearch`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SemanticSearch().with { $0.searchText = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let searchText = CodingKeys(stringValue: "searchText")
    static let searchField = CodingKeys(stringValue: "searchField")
    static let taskType = CodingKeys(stringValue: "taskType")
    static let outputFields = CodingKeys(stringValue: "outputFields")
    static let filter = CodingKeys(stringValue: "filter")
    static let topK = CodingKeys(stringValue: "topK")
    static let searchHint = CodingKeys(stringValue: "searchHint")

    static let _knownKeys: Set<Swift.String> = [
      "searchText",
      "searchField",
      "taskType",
      "outputFields",
      "filter",
      "topK",
      "searchHint",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .searchText) {
      self.searchText = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .searchField) {
      self.searchField = value
    }
    if let value = try container.decodeIfPresent(EmbeddingTaskType.self, forKey: .taskType) {
      self.taskType = value
    }
    self.outputFields = try container.decodeIfPresent(OutputFields.self, forKey: .outputFields)
    self.filter = try container.decodeIfPresent(GoogleWKT.Struct.self, forKey: .filter)
    self.topK = try container.decodeIfPresent(Swift.Int32.self, forKey: .topK)
    self.searchHint = try container.decodeIfPresent(SearchHint.self, forKey: .searchHint)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.searchText, forKey: .searchText)
    try container.encode(self.searchField, forKey: .searchField)
    try container.encode(self.taskType, forKey: .taskType)
    try container.encodeIfPresent(self.outputFields, forKey: .outputFields)
    try container.encodeIfPresent(self.filter, forKey: .filter)
    try container.encodeIfPresent(self.topK, forKey: .topK)
    try container.encodeIfPresent(self.searchHint, forKey: .searchHint)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vectorsearch.v1.SemanticSearch"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
