// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Defines a text search operation.
public struct TextSearch: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. The query text. Required when using the default text search mode.
  public var searchText: Swift.String = Swift.String()

  /// Optional. The data field names to search. Required when using the default
  /// text search mode.
  public var dataFieldNames: [Swift.String] = []

  /// Optional. The fields to return in the search results.
  public var outputFields: OutputFields? = nil

  /// Optional. The number of results to return.
  public var topK: Swift.Int32? = nil

  /// Optional. A JSON filter expression, e.g. `{"genre": {"$eq": "sci-fi"}}`,
  /// represented as a `google.protobuf.Struct`.
  public var filter: GoogleCloudWKT.Struct? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `TextSearch`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TextSearch().with { $0.searchText = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let searchText = CodingKeys(stringValue: "searchText")
    static let dataFieldNames = CodingKeys(stringValue: "dataFieldNames")
    static let outputFields = CodingKeys(stringValue: "outputFields")
    static let topK = CodingKeys(stringValue: "topK")
    static let filter = CodingKeys(stringValue: "filter")

    static let _knownKeys: Set<Swift.String> = [
      "searchText",
      "dataFieldNames",
      "outputFields",
      "topK",
      "filter",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .searchText) {
      self.searchText = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .dataFieldNames) {
      self.dataFieldNames = value
    }
    self.outputFields = try container.decodeIfPresent(OutputFields.self, forKey: .outputFields)
    self.topK = try container.decodeIfPresent(Swift.Int32.self, forKey: .topK)
    self.filter = try container.decodeIfPresent(GoogleCloudWKT.Struct.self, forKey: .filter)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.searchText, forKey: .searchText)
    try container.encode(self.dataFieldNames, forKey: .dataFieldNames)
    try container.encodeIfPresent(self.outputFields, forKey: .outputFields)
    try container.encodeIfPresent(self.topK, forKey: .topK)
    try container.encodeIfPresent(self.filter, forKey: .filter)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vectorsearch.v1.TextSearch"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
