// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class VectorSearchServiceLogging: VectorSearchServiceStub {
    let inner: any VectorSearchServiceStub
    let logger: Logger

    public init(_ inner: any VectorSearchServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-vectorsearch-v1"
      logger[metadataKey: "gcp.client.service"] = "vectorsearch"
      logger[metadataKey: "gcp.experimental.swift.client"] = "VectorSearchService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listCollections(
      request: ListCollectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVectorSearchV1.ListCollectionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCollections",
        action: {
          (r: ListCollectionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVectorSearchV1.ListCollectionsResponse
          in
          return try await self.inner.listCollections(request: r, options: o)
        })
    }

    public func getCollection(
      request: GetCollectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVectorSearchV1.Collection {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCollection",
        action: {
          (r: GetCollectionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVectorSearchV1.Collection
          in
          return try await self.inner.getCollection(request: r, options: o)
        })
    }

    public func createCollection(
      request: CreateCollectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCollection",
        action: {
          (r: CreateCollectionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createCollection(request: r, options: o)
        })
    }

    public func updateCollection(
      request: UpdateCollectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCollection",
        action: {
          (r: UpdateCollectionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateCollection(request: r, options: o)
        })
    }

    public func deleteCollection(
      request: DeleteCollectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCollection",
        action: {
          (r: DeleteCollectionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteCollection(request: r, options: o)
        })
    }

    public func listIndexes(
      request: ListIndexesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVectorSearchV1.ListIndexesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listIndexes",
        action: {
          (r: ListIndexesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVectorSearchV1.ListIndexesResponse
          in
          return try await self.inner.listIndexes(request: r, options: o)
        })
    }

    public func getIndex(
      request: GetIndexRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVectorSearchV1.Index {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIndex",
        action: {
          (r: GetIndexRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVectorSearchV1.Index
          in
          return try await self.inner.getIndex(request: r, options: o)
        })
    }

    public func createIndex(
      request: CreateIndexRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createIndex",
        action: {
          (r: CreateIndexRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createIndex(request: r, options: o)
        })
    }

    public func updateIndex(
      request: UpdateIndexRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateIndex",
        action: {
          (r: UpdateIndexRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateIndex(request: r, options: o)
        })
    }

    public func deleteIndex(
      request: DeleteIndexRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteIndex",
        action: {
          (r: DeleteIndexRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteIndex(request: r, options: o)
        })
    }

    public func importDataObjects(
      request: ImportDataObjectsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "importDataObjects",
        action: {
          (r: ImportDataObjectsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.importDataObjects(request: r, options: o)
        })
    }

    public func exportDataObjects(
      request: ExportDataObjectsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "exportDataObjects",
        action: {
          (r: ExportDataObjectsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.exportDataObjects(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
