// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message describing a vector field.
public struct VectorField: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Vector type configuration.
  public var vectorTypeConfig: VectorTypeConfigOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `VectorField`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VectorField().with { $0.denseVector = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let denseVector = CodingKeys(stringValue: "denseVector")
    static let sparseVector = CodingKeys(stringValue: "sparseVector")

    static let _knownKeys: Set<Swift.String> = [
      "denseVector",
      "sparseVector",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var vectorTypeConfig: VectorTypeConfigOneOf? = nil
    let vectorTypeConfigCheckAndSet = {
      if vectorTypeConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'vectorTypeConfig'"))
      }
      vectorTypeConfig = $0
    }
    if let denseVector = try container.decodeIfPresent(DenseVectorField.self, forKey: .denseVector)
    {
      try vectorTypeConfigCheckAndSet(.denseVector(denseVector))
    }
    if let sparseVector = try container.decodeIfPresent(
      SparseVectorField.self, forKey: .sparseVector)
    {
      try vectorTypeConfigCheckAndSet(.sparseVector(sparseVector))
    }
    self.vectorTypeConfig = vectorTypeConfig
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.vectorTypeConfig {
      switch choice {
      case .denseVector(let value):
        try container.encode(value, forKey: .denseVector)
      case .sparseVector(let value):
        try container.encode(value, forKey: .sparseVector)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Vector type configuration.
  public enum VectorTypeConfigOneOf: Codable, Equatable, Sendable {
    /// Dense vector field.
    indirect case denseVector(DenseVectorField)
    /// Sparse vector field.
    indirect case sparseVector(SparseVectorField)
  }

  /// The type URL for `VectorField`: `"type.googleapis.com/google.cloud.vectorsearch.v1.VectorField"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vectorsearch.v1.VectorField"
  }

  /// Initialize an instance of `VectorField` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.vectorsearch.v1.VectorField"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `VectorField` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
