// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Message describing a vector field.
public struct VectorField: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Vector type configuration.
  public var vectorTypeConfig: OneOf_VectorTypeConfig? = nil

  /// Initialize a new instance of `VectorField`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VectorField().with { $0.denseVector = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case denseVector = "denseVector"
    case sparseVector = "sparseVector"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var vectorTypeConfig: OneOf_VectorTypeConfig? = nil
    let vectorTypeConfigCheckAndSet = {
      if vectorTypeConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'vectorTypeConfig'"))
      }
      vectorTypeConfig = $0
    }
    if let denseVector = try container.decodeIfPresent(DenseVectorField?.self, forKey: .denseVector)
    {
      try vectorTypeConfigCheckAndSet(.denseVector(denseVector))
    }
    if let sparseVector = try container.decodeIfPresent(
      SparseVectorField?.self, forKey: .sparseVector)
    {
      try vectorTypeConfigCheckAndSet(.sparseVector(sparseVector))
    }
    self.vectorTypeConfig = vectorTypeConfig
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.vectorTypeConfig {
      switch choice {
      case .denseVector(let value):
        try container.encode(value, forKey: .denseVector)
      case .sparseVector(let value):
        try container.encode(value, forKey: .sparseVector)
      }
    }
  }

  /// Vector type configuration.
  public enum OneOf_VectorTypeConfig: Codable, Equatable, Sendable {
    /// Dense vector field.
    indirect case denseVector(DenseVectorField?)
    /// Sparse vector field.
    indirect case sparseVector(SparseVectorField?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vectorsearch.v1.VectorField"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
