// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// VectorSearchService provides methods for managing Collection resources, and
/// Collection Index resources. The primary resources offered by this service are
/// Collections which are a container for a set of related JSON data objects, and
/// Collection Indexes which enable efficient ANN search across data objects
/// within a Collection.
///
/// @Snippet(path: "VectorSearchServiceQuickstart")
public final class VectorSearchServiceClient: Clients.VectorSearchServiceProtocol, Sendable {
  let inner: any Clients.VectorSearchServiceStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `VectorSearchServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.VectorSearchServiceStub = try Clients.VectorSearchServiceTransport(
      options)
    inner = Clients.VectorSearchServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.VectorSearchServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists Collections in a given project and location.
  ///
  /// @Snippet(path: "VectorSearchService_ListCollections")
  public func listCollections(
    request: ListCollectionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVectorSearchV1.ListCollectionsResponse {
    try await self.inner.listCollections(request: request, options: options)
  }

  /// Lists Collections in a given project and location.
  ///
  /// @Snippet(path: "VectorSearchService_ListCollections")
  public func listCollections(
    byItem: ListCollectionsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Collection, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVectorSearchV1.ListCollectionsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listCollections(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Collection.
  ///
  /// @Snippet(path: "VectorSearchService_GetCollection")
  public func getCollection(
    request: GetCollectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVectorSearchV1.Collection {
    try await self.inner.getCollection(request: request, options: options)
  }

  /// Creates a new Collection in a given project and location.
  ///
  /// @Snippet(path: "VectorSearchService_CreateCollection")
  public func createCollection(
    request: CreateCollectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createCollection(request: request, options: options)
  }

  /// Creates a new Collection in a given project and location.
  ///
  /// @Snippet(path: "VectorSearchService_CreateCollection")
  public func createCollection(
    withPolling: CreateCollectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Collection> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Collection>.State
      in
      return try op._extractStatus(Collection.self)
    }
    let rawOp = try await self.createCollection(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Collection>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of a single Collection.
  ///
  /// @Snippet(path: "VectorSearchService_UpdateCollection")
  public func updateCollection(
    request: UpdateCollectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateCollection(request: request, options: options)
  }

  /// Updates the parameters of a single Collection.
  ///
  /// @Snippet(path: "VectorSearchService_UpdateCollection")
  public func updateCollection(
    withPolling: UpdateCollectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Collection> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Collection>.State
      in
      return try op._extractStatus(Collection.self)
    }
    let rawOp = try await self.updateCollection(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Collection>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single Collection.
  ///
  /// @Snippet(path: "VectorSearchService_DeleteCollection")
  public func deleteCollection(
    request: DeleteCollectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteCollection(request: request, options: options)
  }

  /// Deletes a single Collection.
  ///
  /// @Snippet(path: "VectorSearchService_DeleteCollection")
  public func deleteCollection(
    withPolling: DeleteCollectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteCollection(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists Indexes in a given project and location.
  ///
  /// @Snippet(path: "VectorSearchService_ListIndexes")
  public func listIndexes(
    request: ListIndexesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVectorSearchV1.ListIndexesResponse {
    try await self.inner.listIndexes(request: request, options: options)
  }

  /// Lists Indexes in a given project and location.
  ///
  /// @Snippet(path: "VectorSearchService_ListIndexes")
  public func listIndexes(
    byItem: ListIndexesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Index, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVectorSearchV1.ListIndexesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listIndexes(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Index.
  ///
  /// @Snippet(path: "VectorSearchService_GetIndex")
  public func getIndex(
    request: GetIndexRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVectorSearchV1.Index {
    try await self.inner.getIndex(request: request, options: options)
  }

  /// Creates a new Index in a given project and location.
  ///
  /// @Snippet(path: "VectorSearchService_CreateIndex")
  public func createIndex(
    request: CreateIndexRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createIndex(request: request, options: options)
  }

  /// Creates a new Index in a given project and location.
  ///
  /// @Snippet(path: "VectorSearchService_CreateIndex")
  public func createIndex(
    withPolling: CreateIndexRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Index> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Index>.State in
      return try op._extractStatus(Index.self)
    }
    let rawOp = try await self.createIndex(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Index>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of a single Index.
  ///
  /// @Snippet(path: "VectorSearchService_UpdateIndex")
  public func updateIndex(
    request: UpdateIndexRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateIndex(request: request, options: options)
  }

  /// Updates the parameters of a single Index.
  ///
  /// @Snippet(path: "VectorSearchService_UpdateIndex")
  public func updateIndex(
    withPolling: UpdateIndexRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Index> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Index>.State in
      return try op._extractStatus(Index.self)
    }
    let rawOp = try await self.updateIndex(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Index>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single Index.
  ///
  /// @Snippet(path: "VectorSearchService_DeleteIndex")
  public func deleteIndex(
    request: DeleteIndexRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteIndex(request: request, options: options)
  }

  /// Deletes a single Index.
  ///
  /// @Snippet(path: "VectorSearchService_DeleteIndex")
  public func deleteIndex(
    withPolling: DeleteIndexRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteIndex(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Initiates a Long-Running Operation to import DataObjects into a Collection.
  ///
  /// @Snippet(path: "VectorSearchService_ImportDataObjects")
  public func importDataObjects(
    request: ImportDataObjectsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.importDataObjects(request: request, options: options)
  }

  /// Initiates a Long-Running Operation to import DataObjects into a Collection.
  ///
  /// @Snippet(path: "VectorSearchService_ImportDataObjects")
  public func importDataObjects(
    withPolling: ImportDataObjectsRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ImportDataObjectsResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<ImportDataObjectsResponse>.State in
      return try op._extractStatus(ImportDataObjectsResponse.self)
    }
    let rawOp = try await self.importDataObjects(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<ImportDataObjectsResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Initiates a Long-Running Operation to export DataObjects from a Collection.
  ///
  /// @Snippet(path: "VectorSearchService_ExportDataObjects")
  public func exportDataObjects(
    request: ExportDataObjectsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.exportDataObjects(request: request, options: options)
  }

  /// Initiates a Long-Running Operation to export DataObjects from a Collection.
  ///
  /// @Snippet(path: "VectorSearchService_ExportDataObjects")
  public func exportDataObjects(
    withPolling: ExportDataObjectsRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ExportDataObjectsResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<ExportDataObjectsResponse>.State in
      return try op._extractStatus(ExportDataObjectsResponse.self)
    }
    let rawOp = try await self.exportDataObjects(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<ExportDataObjectsResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "VectorSearchService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "VectorSearchService_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "VectorSearchService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "VectorSearchService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "VectorSearchService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "VectorSearchService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "VectorSearchService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "VectorSearchService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `VectorSearchServiceClient`.
  ///
  /// To mock `VectorSearchServiceClient` change your functions to receive
  /// `some VectorSearchServiceProtocol` or `any VectorSearchServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol VectorSearchServiceProtocol {
    /// See `VectorSearchServiceClient.listCollections`.
    func listCollections(request: ListCollectionsRequest) async throws
      -> GoogleCloudVectorSearchV1.ListCollectionsResponse

    /// See `VectorSearchServiceClient.listCollections`.
    func listCollections(
      byItem: ListCollectionsRequest
    ) -> any AsyncSequence<Collection, Swift.Error>

    /// See `VectorSearchServiceClient.listCollections`.
    func listCollections(
      parent: Swift.String,
    ) -> any AsyncSequence<Collection, Swift.Error>

    /// See `VectorSearchServiceClient.getCollection`.
    func getCollection(request: GetCollectionRequest) async throws
      -> GoogleCloudVectorSearchV1.Collection

    /// See `VectorSearchServiceClient.getCollection`.
    func getCollection(
      name: Swift.String,
    ) async throws -> GoogleCloudVectorSearchV1.Collection

    /// See `VectorSearchServiceClient.createCollection`.
    func createCollection(request: CreateCollectionRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `VectorSearchServiceClient.createCollection`.
    func createCollection(withPolling: CreateCollectionRequest) async throws -> any GoogleGax
      .PollableOperation<Collection>

    /// See `VectorSearchServiceClient.createCollection`.
    func createCollection(
      parent: Swift.String,
      collection: Collection?,
      collectionId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Collection>

    /// See `VectorSearchServiceClient.updateCollection`.
    func updateCollection(request: UpdateCollectionRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `VectorSearchServiceClient.updateCollection`.
    func updateCollection(withPolling: UpdateCollectionRequest) async throws -> any GoogleGax
      .PollableOperation<Collection>

    /// See `VectorSearchServiceClient.updateCollection`.
    func updateCollection(
      collection: Collection?,
      updateMask: GoogleWKT.FieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<Collection>

    /// See `VectorSearchServiceClient.deleteCollection`.
    func deleteCollection(request: DeleteCollectionRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `VectorSearchServiceClient.deleteCollection`.
    func deleteCollection(withPolling: DeleteCollectionRequest) async throws -> any GoogleGax
      .PollableOperation<Swift.Void>

    /// See `VectorSearchServiceClient.deleteCollection`.
    func deleteCollection(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `VectorSearchServiceClient.listIndexes`.
    func listIndexes(request: ListIndexesRequest) async throws
      -> GoogleCloudVectorSearchV1.ListIndexesResponse

    /// See `VectorSearchServiceClient.listIndexes`.
    func listIndexes(
      byItem: ListIndexesRequest
    ) -> any AsyncSequence<Index, Swift.Error>

    /// See `VectorSearchServiceClient.listIndexes`.
    func listIndexes(
      parent: Swift.String,
    ) -> any AsyncSequence<Index, Swift.Error>

    /// See `VectorSearchServiceClient.getIndex`.
    func getIndex(request: GetIndexRequest) async throws -> GoogleCloudVectorSearchV1.Index

    /// See `VectorSearchServiceClient.getIndex`.
    func getIndex(
      name: Swift.String,
    ) async throws -> GoogleCloudVectorSearchV1.Index

    /// See `VectorSearchServiceClient.createIndex`.
    func createIndex(request: CreateIndexRequest) async throws -> GoogleLongRunning.Operation

    /// See `VectorSearchServiceClient.createIndex`.
    func createIndex(withPolling: CreateIndexRequest) async throws -> any GoogleGax
      .PollableOperation<Index>

    /// See `VectorSearchServiceClient.createIndex`.
    func createIndex(
      parent: Swift.String,
      index: Index?,
      indexId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Index>

    /// See `VectorSearchServiceClient.updateIndex`.
    func updateIndex(request: UpdateIndexRequest) async throws -> GoogleLongRunning.Operation

    /// See `VectorSearchServiceClient.updateIndex`.
    func updateIndex(withPolling: UpdateIndexRequest) async throws -> any GoogleGax
      .PollableOperation<Index>

    /// See `VectorSearchServiceClient.updateIndex`.
    func updateIndex(
      index: Index?,
      updateMask: GoogleWKT.FieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<Index>

    /// See `VectorSearchServiceClient.deleteIndex`.
    func deleteIndex(request: DeleteIndexRequest) async throws -> GoogleLongRunning.Operation

    /// See `VectorSearchServiceClient.deleteIndex`.
    func deleteIndex(withPolling: DeleteIndexRequest) async throws -> any GoogleGax
      .PollableOperation<Swift.Void>

    /// See `VectorSearchServiceClient.deleteIndex`.
    func deleteIndex(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `VectorSearchServiceClient.importDataObjects`.
    func importDataObjects(request: ImportDataObjectsRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `VectorSearchServiceClient.importDataObjects`.
    func importDataObjects(withPolling: ImportDataObjectsRequest) async throws -> any GoogleGax
      .PollableOperation<ImportDataObjectsResponse>

    /// See `VectorSearchServiceClient.exportDataObjects`.
    func exportDataObjects(request: ExportDataObjectsRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `VectorSearchServiceClient.exportDataObjects`.
    func exportDataObjects(withPolling: ExportDataObjectsRequest) async throws -> any GoogleGax
      .PollableOperation<ExportDataObjectsResponse>

    /// See `VectorSearchServiceClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `VectorSearchServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `VectorSearchServiceClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `VectorSearchServiceClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `VectorSearchServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `VectorSearchServiceClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `VectorSearchServiceClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `VectorSearchServiceClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `VectorSearchServiceClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `VectorSearchServiceClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `VectorSearchServiceClient.listCollections`.
    func listCollections(
      request: ListCollectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVectorSearchV1.ListCollectionsResponse

    /// See `VectorSearchServiceClient.listCollections`.
    func listCollections(
      byItem: ListCollectionsRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<Collection, Swift.Error>

    /// See `VectorSearchServiceClient.getCollection`.
    func getCollection(
      request: GetCollectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVectorSearchV1.Collection

    /// See `VectorSearchServiceClient.createCollection`.
    func createCollection(
      request: CreateCollectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VectorSearchServiceClient.createCollection`.
    func createCollection(
      withPolling: CreateCollectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Collection>

    /// See `VectorSearchServiceClient.updateCollection`.
    func updateCollection(
      request: UpdateCollectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VectorSearchServiceClient.updateCollection`.
    func updateCollection(
      withPolling: UpdateCollectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Collection>

    /// See `VectorSearchServiceClient.deleteCollection`.
    func deleteCollection(
      request: DeleteCollectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VectorSearchServiceClient.deleteCollection`.
    func deleteCollection(
      withPolling: DeleteCollectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `VectorSearchServiceClient.listIndexes`.
    func listIndexes(
      request: ListIndexesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVectorSearchV1.ListIndexesResponse

    /// See `VectorSearchServiceClient.listIndexes`.
    func listIndexes(
      byItem: ListIndexesRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<Index, Swift.Error>

    /// See `VectorSearchServiceClient.getIndex`.
    func getIndex(
      request: GetIndexRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVectorSearchV1.Index

    /// See `VectorSearchServiceClient.createIndex`.
    func createIndex(
      request: CreateIndexRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VectorSearchServiceClient.createIndex`.
    func createIndex(
      withPolling: CreateIndexRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Index>

    /// See `VectorSearchServiceClient.updateIndex`.
    func updateIndex(
      request: UpdateIndexRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VectorSearchServiceClient.updateIndex`.
    func updateIndex(
      withPolling: UpdateIndexRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Index>

    /// See `VectorSearchServiceClient.deleteIndex`.
    func deleteIndex(
      request: DeleteIndexRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VectorSearchServiceClient.deleteIndex`.
    func deleteIndex(
      withPolling: DeleteIndexRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `VectorSearchServiceClient.importDataObjects`.
    func importDataObjects(
      request: ImportDataObjectsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VectorSearchServiceClient.importDataObjects`.
    func importDataObjects(
      withPolling: ImportDataObjectsRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<ImportDataObjectsResponse>

    /// See `VectorSearchServiceClient.exportDataObjects`.
    func exportDataObjects(
      request: ExportDataObjectsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VectorSearchServiceClient.exportDataObjects`.
    func exportDataObjects(
      withPolling: ExportDataObjectsRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<ExportDataObjectsResponse>

    /// See `VectorSearchServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `VectorSearchServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `VectorSearchServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `VectorSearchServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `VectorSearchServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `VectorSearchServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `VectorSearchServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.VectorSearchServiceProtocol {
  public func listCollections(request: ListCollectionsRequest) async throws
    -> GoogleCloudVectorSearchV1.ListCollectionsResponse
  {
    try await self.listCollections(request: request, options: .init())
  }

  public func listCollections(
    request: ListCollectionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVectorSearchV1.ListCollectionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listCollections(
    byItem: ListCollectionsRequest
  ) -> any AsyncSequence<Collection, Swift.Error> {
    self.listCollections(byItem: byItem, options: .init())
  }

  public func listCollections(
    byItem: ListCollectionsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Collection, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVectorSearchV1.ListCollectionsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listCollections(
    parent: Swift.String,
  ) -> any AsyncSequence<Collection, Swift.Error> {
    let request = ListCollectionsRequest().with {
      $0.parent = parent
    }
    return self.listCollections(byItem: request)
  }

  public func getCollection(request: GetCollectionRequest) async throws
    -> GoogleCloudVectorSearchV1.Collection
  {
    try await self.getCollection(request: request, options: .init())
  }

  public func getCollection(
    request: GetCollectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVectorSearchV1.Collection {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getCollection(
    name: Swift.String,
  ) async throws -> GoogleCloudVectorSearchV1.Collection {
    let request = GetCollectionRequest().with {
      $0.name = name
    }
    return try await self.getCollection(request: request)
  }

  public func createCollection(request: CreateCollectionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createCollection(request: request, options: .init())
  }

  public func createCollection(
    request: CreateCollectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createCollection(withPolling: CreateCollectionRequest) async throws -> any GoogleGax
    .PollableOperation<Collection>
  {
    try await self.createCollection(withPolling: withPolling, options: .init())
  }

  public func createCollection(
    withPolling: CreateCollectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Collection> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Collection>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createCollection(
    parent: Swift.String,
    collection: Collection?,
    collectionId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Collection> {
    let request = CreateCollectionRequest().with {
      $0.parent = parent
      $0.collection = collection
      $0.collectionId = collectionId
    }
    return try await self.createCollection(withPolling: request)
  }

  public func updateCollection(request: UpdateCollectionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateCollection(request: request, options: .init())
  }

  public func updateCollection(
    request: UpdateCollectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateCollection(withPolling: UpdateCollectionRequest) async throws -> any GoogleGax
    .PollableOperation<Collection>
  {
    try await self.updateCollection(withPolling: withPolling, options: .init())
  }

  public func updateCollection(
    withPolling: UpdateCollectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Collection> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Collection>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateCollection(
    collection: Collection?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Collection> {
    let request = UpdateCollectionRequest().with {
      $0.collection = collection
      $0.updateMask = updateMask
    }
    return try await self.updateCollection(withPolling: request)
  }

  public func deleteCollection(request: DeleteCollectionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteCollection(request: request, options: .init())
  }

  public func deleteCollection(
    request: DeleteCollectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteCollection(withPolling: DeleteCollectionRequest) async throws -> any GoogleGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteCollection(withPolling: withPolling, options: .init())
  }

  public func deleteCollection(
    withPolling: DeleteCollectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteCollection(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteCollectionRequest().with {
      $0.name = name
    }
    return try await self.deleteCollection(withPolling: request)
  }

  public func listIndexes(request: ListIndexesRequest) async throws
    -> GoogleCloudVectorSearchV1.ListIndexesResponse
  {
    try await self.listIndexes(request: request, options: .init())
  }

  public func listIndexes(
    request: ListIndexesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVectorSearchV1.ListIndexesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listIndexes(
    byItem: ListIndexesRequest
  ) -> any AsyncSequence<Index, Swift.Error> {
    self.listIndexes(byItem: byItem, options: .init())
  }

  public func listIndexes(
    byItem: ListIndexesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Index, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVectorSearchV1.ListIndexesResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listIndexes(
    parent: Swift.String,
  ) -> any AsyncSequence<Index, Swift.Error> {
    let request = ListIndexesRequest().with {
      $0.parent = parent
    }
    return self.listIndexes(byItem: request)
  }

  public func getIndex(request: GetIndexRequest) async throws -> GoogleCloudVectorSearchV1.Index {
    try await self.getIndex(request: request, options: .init())
  }

  public func getIndex(
    request: GetIndexRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVectorSearchV1.Index {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getIndex(
    name: Swift.String,
  ) async throws -> GoogleCloudVectorSearchV1.Index {
    let request = GetIndexRequest().with {
      $0.name = name
    }
    return try await self.getIndex(request: request)
  }

  public func createIndex(request: CreateIndexRequest) async throws -> GoogleLongRunning.Operation {
    try await self.createIndex(request: request, options: .init())
  }

  public func createIndex(
    request: CreateIndexRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createIndex(withPolling: CreateIndexRequest) async throws -> any GoogleGax
    .PollableOperation<Index>
  {
    try await self.createIndex(withPolling: withPolling, options: .init())
  }

  public func createIndex(
    withPolling: CreateIndexRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Index> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Index>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createIndex(
    parent: Swift.String,
    index: Index?,
    indexId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Index> {
    let request = CreateIndexRequest().with {
      $0.parent = parent
      $0.index = index
      $0.indexId = indexId
    }
    return try await self.createIndex(withPolling: request)
  }

  public func updateIndex(request: UpdateIndexRequest) async throws -> GoogleLongRunning.Operation {
    try await self.updateIndex(request: request, options: .init())
  }

  public func updateIndex(
    request: UpdateIndexRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateIndex(withPolling: UpdateIndexRequest) async throws -> any GoogleGax
    .PollableOperation<Index>
  {
    try await self.updateIndex(withPolling: withPolling, options: .init())
  }

  public func updateIndex(
    withPolling: UpdateIndexRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Index> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Index>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateIndex(
    index: Index?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Index> {
    let request = UpdateIndexRequest().with {
      $0.index = index
      $0.updateMask = updateMask
    }
    return try await self.updateIndex(withPolling: request)
  }

  public func deleteIndex(request: DeleteIndexRequest) async throws -> GoogleLongRunning.Operation {
    try await self.deleteIndex(request: request, options: .init())
  }

  public func deleteIndex(
    request: DeleteIndexRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteIndex(withPolling: DeleteIndexRequest) async throws -> any GoogleGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteIndex(withPolling: withPolling, options: .init())
  }

  public func deleteIndex(
    withPolling: DeleteIndexRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteIndex(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteIndexRequest().with {
      $0.name = name
    }
    return try await self.deleteIndex(withPolling: request)
  }

  public func importDataObjects(request: ImportDataObjectsRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.importDataObjects(request: request, options: .init())
  }

  public func importDataObjects(
    request: ImportDataObjectsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func importDataObjects(withPolling: ImportDataObjectsRequest) async throws -> any GoogleGax
    .PollableOperation<ImportDataObjectsResponse>
  {
    try await self.importDataObjects(withPolling: withPolling, options: .init())
  }

  public func importDataObjects(
    withPolling: ImportDataObjectsRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ImportDataObjectsResponse> {
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<ImportDataObjectsResponse>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func exportDataObjects(request: ExportDataObjectsRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.exportDataObjects(request: request, options: .init())
  }

  public func exportDataObjects(
    request: ExportDataObjectsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func exportDataObjects(withPolling: ExportDataObjectsRequest) async throws -> any GoogleGax
    .PollableOperation<ExportDataObjectsResponse>
  {
    try await self.exportDataObjects(withPolling: withPolling, options: .init())
  }

  public func exportDataObjects(
    withPolling: ExportDataObjectsRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ExportDataObjectsResponse> {
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<ExportDataObjectsResponse>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
