// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Defines a search operation using a query vector.
public struct VectorSearch: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The vector field to search.
  public var searchField: Swift.String = Swift.String()

  /// Optional. A JSON filter expression, e.g. {"genre": {"$eq": "sci-fi"}},
  /// represented as a google.protobuf.Struct.
  public var filter: GoogleCloudWKT.Struct? = nil

  /// Optional. The number of nearest neighbors to return.
  public var topK: Swift.Int32? = nil

  /// Optional. Mask specifying which fields to return.
  public var outputFields: OutputFields? = nil

  /// Optional. Sets the search hint. If no strategy is specified, the service
  /// will use an index if one is available, and fall back to the default KNN
  /// search otherwise.
  public var searchHint: SearchHint? = nil

  /// Optional. The distance metric to use for the KNN search. If not specified,
  /// DOT_PRODUCT will be used as the default.
  public var distanceMetric: DistanceMetric = DistanceMetric()

  /// Specifies the type of vector to use for the query.
  public var vectorType: OneOf_VectorType? = nil

  /// Initialize a new instance of `VectorSearch`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VectorSearch().with { $0.vector = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case vector = "vector"
    case sparseVector = "sparseVector"
    case searchField = "searchField"
    case filter = "filter"
    case topK = "topK"
    case outputFields = "outputFields"
    case searchHint = "searchHint"
    case distanceMetric = "distanceMetric"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.searchField = try container.decode(Swift.String.self, forKey: .searchField)
    self.filter = try container.decodeIfPresent(GoogleCloudWKT.Struct.self, forKey: .filter)
    self.topK = try container.decodeIfPresent(Swift.Int32.self, forKey: .topK)
    self.outputFields = try container.decodeIfPresent(OutputFields.self, forKey: .outputFields)
    self.searchHint = try container.decodeIfPresent(SearchHint.self, forKey: .searchHint)
    self.distanceMetric = try container.decode(DistanceMetric.self, forKey: .distanceMetric)

    var vectorType: OneOf_VectorType? = nil
    let vectorTypeCheckAndSet = {
      if vectorType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'vectorType'"))
      }
      vectorType = $0
    }
    if let vector = try container.decodeIfPresent(DenseVector?.self, forKey: .vector) {
      try vectorTypeCheckAndSet(.vector(vector))
    }
    if let sparseVector = try container.decodeIfPresent(SparseVector?.self, forKey: .sparseVector) {
      try vectorTypeCheckAndSet(.sparseVector(sparseVector))
    }
    self.vectorType = vectorType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.searchField, forKey: .searchField)
    try container.encode(self.filter, forKey: .filter)
    try container.encode(self.topK, forKey: .topK)
    try container.encode(self.outputFields, forKey: .outputFields)
    try container.encode(self.searchHint, forKey: .searchHint)
    try container.encode(self.distanceMetric, forKey: .distanceMetric)

    if let choice = self.vectorType {
      switch choice {
      case .vector(let value):
        try container.encode(value, forKey: .vector)
      case .sparseVector(let value):
        try container.encode(value, forKey: .sparseVector)
      }
    }
  }

  /// Specifies the type of vector to use for the query.
  public enum OneOf_VectorType: Codable, Equatable, Sendable {
    /// A dense vector for the query.
    indirect case vector(DenseVector?)
    /// A sparse vector for the query.
    indirect case sparseVector(SparseVector?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vectorsearch.v1.VectorSearch"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
