// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A vector which can be either dense or sparse.
public struct Vector: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The type of the vector.
  public var vectorType: OneOf_VectorType? = nil

  /// Initialize a new instance of `Vector`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Vector().with { $0.dense = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case dense = "dense"
    case sparse = "sparse"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var vectorType: OneOf_VectorType? = nil
    let vectorTypeCheckAndSet = {
      if vectorType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'vectorType'"))
      }
      vectorType = $0
    }
    if let dense = try container.decodeIfPresent(DenseVector?.self, forKey: .dense) {
      try vectorTypeCheckAndSet(.dense(dense))
    }
    if let sparse = try container.decodeIfPresent(SparseVector?.self, forKey: .sparse) {
      try vectorTypeCheckAndSet(.sparse(sparse))
    }
    self.vectorType = vectorType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.vectorType {
      switch choice {
      case .dense(let value):
        try container.encode(value, forKey: .dense)
      case .sparse(let value):
        try container.encode(value, forKey: .sparse)
      }
    }
  }

  /// The type of the vector.
  public enum OneOf_VectorType: Codable, Equatable, Sendable {
    /// A dense vector.
    indirect case dense(DenseVector?)
    /// A sparse vector.
    indirect case sparse(SparseVector?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vectorsearch.v1.Vector"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
