// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Defines a ranker using the Vertex AI ranking service.
/// See https://cloud.google.com/generative-ai-app-builder/docs/ranking for
/// details.
public struct VertexRanker: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The model used for ranking documents. The list of available
  /// models is described in
  /// https://docs.cloud.google.com/generative-ai-app-builder/docs/ranking#models.
  /// Currently, only `semantic-ranker-fast@latest` is supported.
  public var model: Swift.String = Swift.String()

  /// Required. The number of documents to be processed for ranking.
  public var topN: Swift.Int32 = Swift.Int32()

  /// The record specification for ranking. At least one record spec must be
  /// set.
  public var recordSpec: OneOf_RecordSpec? = nil

  /// Initialize a new instance of `VertexRanker`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VertexRanker().with { $0.textRecordSpec = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case textRecordSpec = "textRecordSpec"
    case model = "model"
    case topN = "topN"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.model = try container.decode(Swift.String.self, forKey: .model)
    self.topN = try container.decode(Swift.Int32.self, forKey: .topN)

    var recordSpec: OneOf_RecordSpec? = nil
    let recordSpecCheckAndSet = {
      if recordSpec != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'recordSpec'"))
      }
      recordSpec = $0
    }
    if let textRecordSpec = try container.decodeIfPresent(
      VertexRanker.TextRecordSpec?.self, forKey: .textRecordSpec)
    {
      try recordSpecCheckAndSet(.textRecordSpec(textRecordSpec))
    }
    self.recordSpec = recordSpec
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.model, forKey: .model)
    try container.encode(self.topN, forKey: .topN)

    if let choice = self.recordSpec {
      switch choice {
      case .textRecordSpec(let value):
        try container.encode(value, forKey: .textRecordSpec)
      }
    }
  }

  /// The record spec for text search.
  public struct TextRecordSpec: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The query against which the records are ranked and scored.
    public var query: Swift.String = Swift.String()

    /// Optional. The template used to generate the record's title.
    public var titleTemplate: Swift.String = Swift.String()

    /// Optional. The template used to generate the record's content.
    public var contentTemplate: Swift.String = Swift.String()

    /// Initialize a new instance of `TextRecordSpec`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TextRecordSpec().with { $0.query = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vectorsearch.v1.VertexRanker.TextRecordSpec"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The record specification for ranking. At least one record spec must be
  /// set.
  public enum OneOf_RecordSpec: Codable, Equatable, Sendable {
    /// The record spec for text search.
    indirect case textRecordSpec(VertexRanker.TextRecordSpec?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vectorsearch.v1.VertexRanker"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
